import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({children,}: Readonly<{children: React.ReactNode }>) 
{ 
 const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <Header  session={session} />
           {children}
      </body>
    </html>
  );
}
